language: c
compiler:
  - clang
  - gcc

sudo: false

addons:
  sources:
    - chris-lea-zeromq
  apt:
    - zeromq
    - intltool
    - libzmq3-dev
    - libmicrohttpd-dev

before_install:
  - sh autogen.sh

script: ./configure && make && make check
