language: c
sudo: false

addons:
  apt:
    sources:
      - chris-lea-zeromq
    packages:
      - zeromq
      - intltool
      - libzmq3-dev
      - libmicrohttpd-dev

compiler:
  - clang
  - gcc

before_install:
  - sh autogen.sh

script: ./configure && make && make check
